name: Promote Python Package

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version to promote (e.g., 0.0.1)'
        required: true
        type: string

env:
  CLOUDSMITH_NAMESPACE: ${{ secrets.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'production'
  PACKAGE_NAME: 'example_package'

permissions:
  id-token: write
  contents: read

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      - name: Get package identifier and promote
        run: |
          PACKAGE_FILE="${PACKAGE_NAME}-${{ github.event.inputs.package_version }}.tar.gz"
          echo "Looking for: $PACKAGE_FILE"

          PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} \
            -q "filename:$PACKAGE_FILE" -F json)

          IDENTIFIER=$(echo "$PACKAGE_DATA" | jq -r '.data[0].identifier_perm')

          if [ -z "$IDENTIFIER" ] || [ "$IDENTIFIER" = "null" ]; then
            echo "❌ Failed to find package with filename: $PACKAGE_FILE"
            echo "Full Cloudsmith response:"
            echo "$PACKAGE_DATA"
            exit 1
          fi

          echo "✅ Found package identifier: $IDENTIFIER"

          echo "Promoting to production..."
          cloudsmith mv --yes \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
            ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
        shell: bash
